user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    access_log /var/log/nginx/access.log;

    server {
        listen 8001;
        server_name _;
        root /usr/share/nginx/html/telecom-http;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }

    server {
        listen 8002;
        server_name _;
        root /usr/share/nginx/html/info-http;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }

    server {
        listen 8003;
        server_name _;
        root /usr/share/nginx/html/electro-http;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }

    server {
        listen 1443 ssl;
        server_name _;
        ssl_certificate /etc/nginx/certs/sdn-server.pem;
        ssl_certificate_key /etc/nginx/certs/sdn-server.key;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        root /usr/share/nginx/html/telecom-https;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }

    server {
        listen 2443 ssl;
        server_name _;
        ssl_certificate /etc/nginx/certs/sdn-server.pem;
        ssl_certificate_key /etc/nginx/certs/sdn-server.key;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        root /usr/share/nginx/html/info-https;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }

    server {
        listen 3443 ssl;
        server_name _;
        ssl_certificate /etc/nginx/certs/sdn-server.pem;
        ssl_certificate_key /etc/nginx/certs/sdn-server.key;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        root /usr/share/nginx/html/electro-https;
        index index.html;
        location / { try_files $uri $uri/ =404; }
    }
}
