version: '3.8'

networks:
  onos_sw_net:
    driver: ipvlan
    driver_opts:
      parent: ens4
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1
  onos_mgmt_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  onos1:
    image: onosproject/onos:2.7.0
    hostname: onos1
    networks:
      onos_sw_net:
        ipv4_address: 192.168.200.201
      onos_mgmt_net:
        ipv4_address: 172.30.0.11
    environment:
      - ONOS_APPS=drivers,openflow
    volumes:
      - ./cluster.json:/root/onos/config/cluster.json
  onos2:
    image: onosproject/onos:2.7.0
    hostname: onos2
    networks:
      onos_sw_net:
        ipv4_address: 192.168.200.202
      onos_mgmt_net:
        ipv4_address: 172.30.0.12
    volumes:
      - ./cluster.json:/root/onos/config/cluster.json
  onos3:
    image: onosproject/onos:2.7.0
    hostname: onos3
    networks:
      onos_sw_net:
        ipv4_address: 192.168.200.203
      onos_mgmt_net:
        ipv4_address: 172.30.0.13
    volumes:
      - ./cluster.json:/root/onos/config/cluster.json

  haproxy:
    image: haproxy:2.9-alpine
    network_mode: host
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - onos1
      - onos2
      - onos3
    restart: unless-stopped