apiVersion: 1

datasources:
  - uid: tempo
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

    jsonData:
      serviceMap:
        datasourceUid: ""

      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false

      nodeGraph:
        enabled: true

      search:
        hide: false