version: "3.9"

services:
  ## DB
  db:
    extends:
      file: ../db/docker-compose.yaml
      service: db
    container_name: db-sql

  ## M1 - Autenticación
  radius:
    extends:
      file: ../app/m1/docker-compose.yaml
      service: radius
    container_name: m1-radius_server

  portal:
    extends:
      file: ../app/m1/docker-compose.yaml
      service: portal
    container_name: m1-portal_auth

  ## M2 - Políticas
  opa:
    extends:
      file: ../app/m2_policies/docker-compose.yaml
      service: opa
    container_name: m2-opa

  sync:
    extends:
      file: ../app/m2_policies/docker-compose.yaml
      service: sync
    container_name: m2-sync

  ## M6 - Traductor
  # m6:
  #  extends:
  #    file: ../app/m6/docker-compose.yaml
  #    service: m6
  #  container_name: m6-service
